#! /usr/bin/env ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'pry-byebug'
  gem 'activesupport', require: 'active_support/all'
end

require 'pathname'

root_dir = Pathname.new(__dir__).join('..')

Pry.start
